#+TITLE: my dynamic window manager config
#+TODO: TODO(t) DEL(D) | DONE(d)
* Inbox
** TODO Volume/brightness scripts should use dunst UI
can copy from old xmonad config

add scripts either to dotfiles =~/.local/bin= or dwm repo
** TODO Configure st
Automatically attach to or create tmux server on opened window
* Patches
** Applied
*** [[https://dwm.suckless.org/patches/attachbottom/][attachbottom]]
New clients open at the bottom of the stack, instead of replacing master.
*** [[https://dwm.suckless.org/patches/autostart][autostart]]
Run the script =~/.local/share/dwm/autostart.sh= at startup.
*** [[https://dwm.suckless.org/patches/cursorwarp][cursorwarp]]
Cursor is automatically moved to middle of window whenever focus shifts.  Focus
doesn't shift when creating/killing windows, but I might replace this diff with
that diff.
*** [[https://dwm.suckless.org/patches/deck][deck]]
Layout: Only two windows, master and first window on stack, are shown.
*** [[https://dwm.suckless.org/patches/movestack][movestack]]
=s-S-J= and =s-S-K= to move windows around stack, a la xmonad.
*** [[https://dwm.suckless.org/patches/systray][systray]]
System tray icons are displayed on the dwm bar.
** Planned additions
*** TODO [[https://dwm.suckless.org/patches/focusmaster/][focusmaster]]
Key to focus the master window immediately.
*** TODO [[https://dwm.suckless.org/patches/inplacerotate/][inplacerotate]]
(Hopefully) rotate clients in stack without disturbing master or focus.  This
would be useful in the deck layout to "flip through" windows in the stack.
*** TODO [[https://dwm.suckless.org/patches/smartborders][smartborders]]
Remove border when fullscreen
*** TODO tabindicators (?)
*** TODO centeredmaster
